
platform :ios, '11.0'

target 'PhotoViewer' do
  use_frameworks!

  pod 'Alamofire'
  pod 'ProgressHUD'
  pod 'SDWebImage'
  pod 'AMShimmer'
  
  target 'PhotoViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoViewerUITests' do
    # Pods for testing
  end

end
